### ISSUE TITLE
FLSAM.control exemple doesn't work

### ISSUE THREAD

**Issue by PierreCalvy** [flr/FLSAM#10]
This message to pay your attention on FLSAM.control function : The exemple FLSAM.control(NSH,NSH.tun) doesn't work :
Error in setup.sam.data(surveys = surveysFLR, residual.fleets = residual.fleets, : arguments inutilisés (residual.fleets = residual.fleets, sum.residual.fleets = sum.fleets)

**Comment by PierreCalvy** [comment]
Thanks, it works with R.4.0.2 but the problem appears again with R 4.0.3

**Comment by iagomosqueira** [comment]
I have now tested both in Linux and Windows 10 64 bit, using R 4.0.3, installing FLSAM 2.1.1 from the FLR repository, after having installed the required version of stockassessment from github, and the example runs fine.

```
> library(FLSAM)
> data(NSH)
> ctrl <- FLSAM.control(NSH,NSH.tun)
```

Can you confirm you have the right version of `stockassessment` installed? You need [rtools](https://cran.r-project.org/bin/windows/Rtools/) in your machine and then call

```
devtools::install_github('fishfollower/SAM/stockassessment', ref='components')
```

**Comment by PierreCalvy** [comment]
Thank you, I have removed and reinstalled **stockassessment** in this way and it works

**Comment by iagomosqueira** [comment]
Perfect. We are trying to find a better way of distributing it. Also, FLSAM will not load if the version of stockassessment is incorrect, 447be19c4871b26d892cdd458c28501824c345f4. Thanks for highlighting this issue.
