### ISSUE TITLE
typo on GitHub page

### ISSUE THREAD

**Issue by mebrooks** [flr/FLSAM#5]
I tried to do a pull request, but it's not in the code, so GitHub won't let me. 
The top of the page
> FLR version of Ander Nielse's SAM stock assessment model

has typos in Anders's name. It should probably be changed to 

>FLR version of Nielsen and Berg's (2014) SAM stock assessment model

to refer to the publication

**Comment by iagomosqueira** [comment]
Description now reads

FLR wrapper to the SAM state-space assessment model
