### ISSUE TITLE
typo on http://www.flr-project.org/FLSAM/

### ISSUE THREAD

**Issue by hgerritsen** [flr/FLSAM#7]
devtools::install_github(‘fishwollower/SAM/stockassessment’, ref=‘component’)

it should be: 'fishfollower'
and 'components'
also the single quotes don't copy correctly from the pdf (‘) vs (')

This line is correct on the github page but not in the flr-project page. Its a bit pedantic but it can take a lot of time to get to the bottom of these things.

**Comment by iagomosqueira** [comment]
Thanks, the html pages had not been updated with the new version of REDAME.md. Done now.
